//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    
    public partial class EmpleadoGetAll_Result1
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<byte> IdArea { get; set; }
        public string NombreArea { get; set; }
        public Nullable<System.DateTime> Column1 { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
    }
}
